### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by mhungerford** [martinhaefner/simppl#15]
This is a really cool project, I like having the C++ interface do all the work of exporting the DBus interface.
Unfortunately the "loose" license description doesn't allow me to use in my projects, as "CopyLeft" means that all the code for the application would essentially have to be fully opensource, even libraries used by the app.
https://en.wikipedia.org/wiki/Copyleft

Most of the other dbus c++ libraries are GPL or lGPLv3, or have to do the whole xmlgen thing (which I hate having the definition autogenerated or in both the C++ class and the xml file).

Would you consider additionally licensing your library under BSD/Apache/MIT?

**Comment by martinhaefner** [comment]
Added an MIT licsense to the current development branch (new_serialization).
