### ISSUE TITLE
Example server returns incomplete introspection description

### ISSUE THREAD

**Issue by Jokymon** [martinhaefner/simppl#19]
The result of a call to `org.freedesktop.DBus.Introspectable.Introspect` returns only a part of the XML description.

Running the example echo server and then doing

```$ dbus-send --session --dest=simppl.example.EchoService.myEcho --type=method_call --print-reply /simppl/example/EchoService/myEcho org.freedesktop.DBus.Introspectable.Introspect```

returns

```
method return time=1586000720.473462 sender=:1.357 -> destination=:1.360 serial=13 reply_serial=2
    string "<?xml version="1.0" ?>
<node name="/simppl/example/EchoService/myEcho">
  <interface name="simppl.example.EchoService"
$
```

At this point the string suddenly ends.

The issue occured on `master` with commit 86dcdb302e6369165392fb50e7a925147a000e54

**Comment by martinhaefner** [comment]
Thanks for creating pull request. Merged into master.
